server:
  port: ${PORT:8761}

spring:
  config:
    import: "optional:configserver:"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0